### ISSUE TITLE
Problems with load_from_msp.py

### ISSUE THREAD

**Issue by mansoldof** [hcji/DeepMASS2_GUI#1]
Hi,
I followed the installation guide (Version 0.99.1), but when I tried to run it I got the following error:

(deepmass) G:\DeepMASS2_GUI>python DeepMASS2.py
Traceback (most recent call last):
  File "DeepMASS2.py", line 39, in <module>
    from core.importing.load_from_files import load_from_files
  File "G:\DeepMASS2_GUI\core\importing\load_from_files.py", line 16, in <module>
    from core.importing.load_from_mat import load_from_mat
  File "G:\DeepMASS2_GUI\core\importing\load_from_mat.py", line 14, in <module>
    from matchms.importing.load_from_msp import _parse_line_with_peaks
ImportError: cannot import name '_parse_line_with_peaks' from 'matchms.importing.load_from_msp' (C:\Users\admin\anaconda3\envs\deepmass\lib\site-packages\matchms\importing\load_from_msp.py)

any idea?

thanks

**Comment by hcji** [comment]
The issue is due to a version mismatch in the `matchms` library. Since matchms is updated frequently, certain functions (such as `_parse_line_with_peaks`) may have been modified, renamed, or removed in newer versions. Please install the corresponding version using `requirements.txt` to ensure compatibility.

**Comment by mansoldof** [comment]
Thank you, I will test and let you know,
my best

**Comment by mansoldof** [comment]
Dear @hcji ,
Unfortunately it seems that the bug persists. Please see:

(deepmass) C:\Users\Planck\Documents\DeepMASS2_GUI>python DeepMASS2.py
Traceback (most recent call last):
  File "DeepMASS2.py", line 39, in <module>
    from core.importing.load_from_files import load_from_files
  File "C:\Users\Planck\Documents\DeepMASS2_GUI\core\importing\load_from_files.py", line 16, in <module>
    from core.importing.load_from_mat import load_from_mat
  File "C:\Users\Planck\Documents\DeepMASS2_GUI\core\importing\load_from_mat.py", line 14, in <module>
    from matchms.importing.load_from_msp import _parse_line_with_peaks
ImportError: cannot import name '_parse_line_with_peaks' from 'matchms.importing.load_from_msp' (C:\Users\Planck\anaconda3\envs\deepmass\lib\site-packages\matchms\importing\load_from_msp.py)


thanks

**Comment by hcji** [comment]
Could you please use `pip list` and check the version number of `matchms`?

**Comment by mansoldof** [comment]
Hi @hcji 
It's 
matchms            0.17.0

check the complete list:
(deepmass) G:\DeepMASS2_GUI>pip list
Package            Version
------------------ -----------
beautifulsoup4     4.12.2
certifi            2024.8.30
charset-normalizer 3.4.0
colorama           0.4.6
cycler             0.12.1
Deprecated         1.2.14
fonttools          4.54.1
gensim             4.3.2
hnswlib            0.6.2
idna               3.10
importlib_metadata 8.5.0
joblib             1.4.2
JPype1             1.4.1
kiwisolver         1.4.7
llvmlite           0.40.1
lxml               5.3.0
matchms            0.17.0
matplotlib         3.5.3
molmass            2023.4.10
networkx           3.1
numba              0.57.1
numpy              1.24.3
packaging          24.1
pandas             2.0.3
pickydict          0.5.0
pillow             10.4.0
pip                24.2
pyparsing          3.1.4
PyQt5              5.15.10
PyQt5-Qt5          5.15.2
PyQt5_sip          12.15.0
pyteomics          4.7.4
python-dateutil    2.9.0.post0
pytz               2024.2
rdkit-pypi         2022.9.5
requests           2.32.3
scikit-learn       1.1.3
scikit-opt         0.6.6
scipy              1.10.1
seaborn            0.13.0
setuptools         75.1.0
six                1.16.0
smart-open         7.0.5
soupsieve          2.6
spec2vec           0.8.0
threadpoolctl      3.5.0
tqdm               4.66.1
tzdata             2024.2
urllib3            2.2.3
wheel              0.44.0
wrapt              1.16.0
zipp               3.20.2

--

**Comment by hcji** [comment]
please install matchms==0.24.2, it should work.

**Comment by mansoldof** [comment]
We went through the installation stage. Now I'm having problems with the program startup.

When starting, this error appears:
![image](https://github.com/user-attachments/assets/41373f12-3001-4d0c-907c-3dcc6b6087f1)

and then it stops at 24%:
![image](https://github.com/user-attachments/assets/691def78-87b8-460a-baf0-32d21dca0092)

However, I followed through and placed all the files in data and model, see:

data:
 Directory of G:\DeepMASS2_GUI\data

10/14/2024  10:30 PM    <DIR>          .
10/14/2024  10:30 PM    <DIR>          ..
10/14/2024  10:06 PM                 0 .placeholder
10/14/2024  10:09 PM       144,802,544 DeepMassStructureDB-v1.0.csv
10/14/2024  10:15 PM       133,387,928 references_index_negative_spec2vec.bin
10/14/2024  10:21 PM       512,011,188 references_index_positive_spec2vec.bin
10/14/2024  10:18 PM       222,714,068 references_spectrums_negative.pickle
10/14/2024  10:27 PM       807,998,025 references_spectrums_positive.pickle
               6 File(s)  1,820,913,753 bytes
               2 Dir(s)  327,973,863,424 bytes free


model:
 Directory of G:\DeepMASS2_GUI\model

10/14/2024  10:30 PM    <DIR>          .
10/14/2024  10:30 PM    <DIR>          ..
10/14/2024  10:06 PM                 0 .placeholder
10/14/2024  10:07 PM         3,377,916 Ms2Vec_allGNPSnegative.hdf5
10/14/2024  10:10 PM       117,046,928 Ms2Vec_allGNPSnegative.hdf5.syn1neg.npy
10/14/2024  10:12 PM       117,046,928 Ms2Vec_allGNPSnegative.hdf5.wv.vectors.npy
10/14/2024  10:11 PM         3,397,039 Ms2Vec_allGNPSpositive.hdf5
10/14/2024  10:13 PM       117,702,128 Ms2Vec_allGNPSpositive.hdf5.syn1neg.npy
10/14/2024  10:13 PM       117,702,128 Ms2Vec_allGNPSpositive.hdf5.wv.vectors.npy
               7 File(s)    476,273,067 bytes
               2 Dir(s)  327,973,863,424 bytes free

----
Thanks

**Comment by hcji** [comment]
Please use DeepMassStructureDB-v1.1.csv [here](https://github.com/hcji/DeepMASS2_GUI/releases/tag/v0.99.1)

**Comment by mansoldof** [comment]
Hi,
This time it opened without problems. However, when testing the example mgf "minimum_example.mgf", there was a bug:

(deepmass) G:\DeepMASS2_GUI> python DeepMASS2.py
Traceback (most recent call last):
  File "DeepMASS2.py", line 414, in fill_formula_table
    self.fill_structural_table()
  File "DeepMASS2.py", line 433, in fill_structural_table
    self.fill_reference_table()
  File "DeepMASS2.py", line 381, in fill_reference_table
    self.plot_spectrum()
  File "DeepMASS2.py", line 452, in plot_spectrum
    self.plot_mol()
  File "DeepMASS2.py", line 490, in plot_mol
    Draw.MolToFile(mol_anno, 'temp/{}.png'.format(file_name), wedgeBonds=False, highlightAtoms=allsubs_anno)
  File "C:\Users\admin\anaconda3\envs\deepmass\lib\site-packages\rdkit\Chem\Draw\__init__.py", line 312, in MolToFile
    with open(filename, 'w+' + mode) as outf:
FileNotFoundError: [Errno 2] No such file or directory: 'temp/VXJ7AHGP53.png'

**Comment by hcji** [comment]
you need create a folder named `temp` in your file path under `DeepMASS `. We fix this in the lastest commit. Thanks for you feedback

**Comment by mansoldof** [comment]
Hi, great, everything worked perfectly,
thank you
